### ISSUE TITLE
libEGL warning: failed to create a pipe screen for i965

### ISSUE THREAD

**Issue by itravers** [raeleus/skin-composer#11]
Running Ubuntu Desktop 14

The window comes up. I can see the title bar.
The window captures an image of the desktop behind it.
(Everything on the desktop behind the window, now shows in the window, and doesn't change no matter where you move the window to.)
The window doesn't do anything else.

I tried Version  5, 6 jars from both the linux download and the jar download. (In your releases page). They both had the same problem.

Version 4 worked fine.

java -jar skin_composer.jar
java.lang.NullPointerException
    at org.lwjgl.system.APIUtil.apiGetManifestValue(APIUtil.java:97)
    at org.lwjgl.system.Library.checkHash(Library.java:260)
    at org.lwjgl.system.Library.<clinit>(Library.java:44)
    at org.lwjgl.system.MemoryAccess.<clinit>(MemoryAccess.java:17)
    at org.lwjgl.system.ThreadLocalUtil$UnsafeState.<clinit>(ThreadLocalUtil.java:86)
    at org.lwjgl.system.ThreadLocalUtil.getInstance(ThreadLocalUtil.java:43)
    at org.lwjgl.system.ThreadLocalUtil.<clinit>(ThreadLocalUtil.java:20)
    at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:577)
    at org.lwjgl.system.Callback.<clinit>(Callback.java:35)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:87)
    at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:42)
libEGL warning: failed to create a pipe screen for i965
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

**Comment by raeleus** [comment]
That's pretty odd. I'm sorry you had to discover that. I currently do my Linux testing on a Linux Mint virtual machine and I didn't come across that. Linux Mint is supposedly a derivative of Ubuntu as well...

In any case, I'll wire up an Ubuntu distro and do some serious Linux testing soon. Does Ubuntu allow you to choose what JRE you can use? I would use the Oracle JRE if that's even an option. Thanks for your report.

**Comment by raeleus** [comment]
Doing some digging, I believe this to be a related issue: https://github.com/LWJGL/lwjgl3/issues/205

I'll still have to create some tests before I elevate this issue to the next responsible party, however it might be an Intel or GPU specific thing. Everything I run is AMD/ATI. Can you run the following jar and tell me if it renders?

[Quantum Horizon.zip](https://github.com/raeleus/skin-composer/files/509721/Quantum.Horizon.zip)

This is one of my skin examples running on LWJGL 3. It doesn't do anything special so it'll narrow down the problem. You'll have to mark it for execution of course. Thanks!

**Comment by itravers** [comment]
Nope, Quantum Horizon has the same exact issue.
Sound like the same problem described in LWJGL/lwjgl3#205

**Comment by raeleus** [comment]
The folks at the LibGDX github page want to know what kernel you're using:

> Maybe ask him which kernel does he use?

**Comment by raeleus** [comment]
The folks at LibGDX say this is fixed with LWJGL3.1. I'm sorry that I can't confirm.
