### ISSUE TITLE
NPE while importing skins

### ISSUE THREAD

**Issue by bvn13** [raeleus/skin-composer#115]
```
java.lang.NullPointerException
	at com.ray3k.skincomposer.data.JsonData.set(JsonData.java:1321)
	at com.ray3k.skincomposer.data.ProjectData.read(ProjectData.java:630)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1011)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:768)
	at com.ray3k.skincomposer.data.ProjectData.load(ProjectData.java:426)
	at com.ray3k.skincomposer.MainListener.lambda$openFile$3(MainListener.java:312)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:159)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:510)
```

Skins tried:
1. [libgdx / gdx-tools](https://github.com/libgdx/libgdx/tree/master/extensions/gdx-tools/assets)
2. [czyzby / gdx-skins / holo](https://github.com/czyzby/gdx-skins/tree/master/holo)

**Comment by bvn13** [comment]
My fault, I was opening file not importing it. 
Not an issue.
