### ISSUE TITLE
Error creating preview font from file. Check file paths.

### ISSUE THREAD

**Issue by jordanbates** [raeleus/skin-composer#12]
"Error creating preview font from file. Check file paths." is the error I get when trying to load in a .fnt file for a label which I created with Littera. Perhaps I'm doing something wrong? I can't find any information about what else I might need to do.

Here's the log:

```
com.ray3k.skincomposer.dialog.DialogFonts: Error creating preview font from file
com.badlogic.gdx.utils.GdxRuntimeException: Error loading font file: C:/Users/Jordan/Documents/Skin Composer/hueboxi_data/HelveticaNeue-Light.fnt
	at com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.load(BitmapFont.java:665)
	at com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.<init>(BitmapFont.java:475)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:114)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:107)
	at com.ray3k.skincomposer.dialog.DialogFonts.fontNameDialog(DialogFonts.java:729)
	at com.ray3k.skincomposer.dialog.DialogFonts.fontNameDialog(DialogFonts.java:676)
	at com.ray3k.skincomposer.dialog.DialogFonts.newFontDialogWindows(DialogFonts.java:634)
	at com.ray3k.skincomposer.dialog.DialogFonts.newFontDialog(DialogFonts.java:611)
	at com.ray3k.skincomposer.dialog.DialogFonts.access$100(DialogFonts.java:82)
	at com.ray3k.skincomposer.dialog.DialogFonts$2.changed(DialogFonts.java:167)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:198)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:257)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:42)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.load(BitmapFont.java:486)
	... 23 more
```

**Comment by raeleus** [comment]
I'm having trouble finding the font you used. The only version I found is an OTF file and it seems to me that Littera only accepts TTF files. Do you mind sharing the FNT file and associated texture PNG with me?

**Comment by jordanbates** [comment]
Sure. I did use a TTF file. Here's that stuff: [HelveticaNeue-Light.zip](https://github.com/raeleus/skin-composer/files/528624/HelveticaNeue-Light.zip)

**Comment by raeleus** [comment]
It looks like you exported the FNT file in an XML format. LibGDX in general won't be able to read that type. Try exporting from Littera using the Text (.fnt) format. Good luck!

**Comment by jordanbates** [comment]
Thank you! It's working perfectly now.
