### ISSUE TITLE
Save skin Error

### ISSUE THREAD

**Issue by Saradey** [raeleus/skin-composer#122]
When trying to save, a crash occurs:
Device: apple macbook m1

[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_nfd.dylib
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:481)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_nfd.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:164)
	at org.lwjgl.util.nfd.LibNFD.<clinit>(LibNFD.java:17)
	at org.lwjgl.util.nfd.NativeFileDialog.<clinit>(NativeFileDialog.java:65)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.saveDialog(DesktopLauncher.java:303)
	at com.ray3k.skincomposer.MainListener.lambda$saveAsFile$11(MainListener.java:444)
	at com.ray3k.skincomposer.dialog.DialogLoading.lambda$show$2(DialogLoading.java:60)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.run(RunnableAction.java:42)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.act(RunnableAction.java:32)
	at com.badlogic.gdx.scenes.scene2d.actions.SequenceAction.act(SequenceAction.java:65)
	at com.badlogic.gdx.scenes.scene2d.Actor.act(Actor.java:98)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:47)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:50)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:226)
	at com.ray3k.skincomposer.Main.render(Main.java:317)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	... 1 more
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.

**Comment by raeleus** [comment]
For now, try starting skin composer with the -swingfd option:
`java -jar SkinComposer.jar -swingfd`

**Comment by raeleus** [comment]
I'm going to close this because the -swingfd option seems to be the only viable solution for me.
