### ISSUE TITLE
Pressing Import File button crashes application on M1 Mac

### ISSUE THREAD

**Issue by psj505** [raeleus/skin-composer#127]
Within Select Drawable screen->Add...->Image File. Application crashes when Image File button is pressed. 

Jdk: Openjdk 15.0.3 2021-04-20
macOS: 11.2.3

Crashes on versions 50 through 52. Versions 49 and below, Jar doesn't run.

Terminal Output:
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_nfd.dylib
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:484)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_nfd.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:164)
	at org.lwjgl.util.nfd.LibNFD.<clinit>(LibNFD.java:17)
	at org.lwjgl.util.nfd.NFDPathSet.<clinit>(NFDPathSet.java:29)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.openMultipleDialog(DesktopLauncher.java:225)
	at com.ray3k.skincomposer.dialog.DialogDrawables.lambda$newDrawableDialog$12(DialogDrawables.java:1967)
	at com.ray3k.skincomposer.dialog.DialogLoading.lambda$show$2(DialogLoading.java:60)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.run(RunnableAction.java:42)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.act(RunnableAction.java:32)
	at com.badlogic.gdx.scenes.scene2d.actions.SequenceAction.act(SequenceAction.java:65)
	at com.badlogic.gdx.scenes.scene2d.Actor.act(Actor.java:98)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:47)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:50)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:226)
	at com.ray3k.skincomposer.Main.render(Main.java:317)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        ... 1 more

**Comment by SandroMoretti** [comment]
Same on my windows

**Comment by raeleus** [comment]
This will be resolved in the next version. Thanks.
