### ISSUE TITLE
com.ray3k.skincomposer.panel.PanelMenuBar: Error attempting to import JSON

### ISSUE THREAD

**Issue by felixvolz** [raeleus/skin-composer#13]
I like the look of skin-composer but cant make it work / or understand why it cant parse the a libgdx uiskin.json

I managed to get your dark-peel json working but nothing else

I've attached the error log and corresponding uiskin.json 
 
`com.ray3k.skincomposer.panel.PanelMenuBar: Error attempting to import JSON
java.lang.NullPointerException
	at com.ray3k.skincomposer.data.JsonData.readFile(JsonData.java:141)
	at com.ray3k.skincomposer.panel.PanelMenuBar.lambda$importDialogWindows$34(PanelMenuBar.java:610)
	at com.ray3k.skincomposer.dialog.DialogLoading.lambda$show$16(DialogLoading.java:56)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.run(RunnableAction.java:42)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.act(RunnableAction.java:32)
	at com.badlogic.gdx.scenes.scene2d.actions.SequenceAction.act(SequenceAction.java:65)
	at com.badlogic.gdx.scenes.scene2d.Actor.act(Actor.java:95)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:46)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:221)
	at com.ray3k.skincomposer.Main.render(Main.java:288)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:255)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:42)

![font](https://cloud.githubusercontent.com/assets/6946906/20302252/a1ed26fa-ab7a-11e6-83ce-05241901d8e2.png)

![uiskin](https://cloud.githubusercontent.com/assets/6946906/20302253/a1f2f9a4-ab7a-11e6-9770-5ccd7e2effef.png)

![uiskin](https://cloud.githubusercontent.com/assets/6946906/20302257/a79e20cc-ab7a-11e6-87cc-5c753ffdbaa6.png)

`

**Comment by felixvolz** [comment]
..and looks like its because I didnt have the font file in the right folder :-)
