### ISSUE TITLE
MacOS Sonoma 14.4.1 Can't run

### ISSUE THREAD

**Issue by isirinz** [raeleus/skin-composer#148]
Sonoma 14.4.1
OpenJDK 21.0.2 2024-01-16

java -jar SkinComposer.jar

`java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1108)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.restartStartOnFirstThread(DesktopLauncher.java:557)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:460)`

**Comment by simanglam** [comment]
Hey,
I have same problem, but it solved after I add `-XstartOnFirstThread` option.
So the command look like:
`java -XstartOnFirstThread -jar SkinComposer.jar`

**Comment by raeleus** [comment]
This should be resolved with the latest update.
