### ISSUE TITLE
Crash after trying to create a new project with any template other than plain Scene2D skin using the splash screen

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#17]
I keep on getting this error when trying to use the new splash screen features:

```
com.badlogic.gdx.utils.GdxRuntimeException: Error copying source file: templates/vis-ui (Internal)
To destination: temp/vis-ui (Local)
	at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:684)
	at com.badlogic.gdx.files.FileHandle.copyTo(FileHandle.java:574)
	at com.ray3k.skincomposer.MainListener$WelcomeDialogListener.visUIclicked(MainListener.java:631)
	at com.ray3k.skincomposer.dialog.DialogWelcome$WelcomeListener.handle(DialogWelcome.java:340)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.ray3k.skincomposer.dialog.DialogWelcome$4.changed(DialogWelcome.java:144)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:190)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:380)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:49)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error stream writing to file: temp/vis-ui (Local)
	at com.badlogic.gdx.files.FileHandle.write(FileHandle.java:296)
	at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:682)
	... 20 more
Caused by: java.lang.NullPointerException
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.badlogic.gdx.utils.StreamUtils.copyStream(StreamUtils.java:49)
	at com.badlogic.gdx.utils.StreamUtils.copyStream(StreamUtils.java:36)
	at com.badlogic.gdx.files.FileHandle.write(FileHandle.java:294)
	... 21 more
```

**Comment by raeleus** [comment]
Dammit. I'll take a look at it today. Is it Linux you're running on?

**Comment by czyzby** [comment]
Yes, Linux Mint 18.1, OpenJDK 8.

**Comment by raeleus** [comment]
Turns out it was a rookie mistake affecting all platforms. Libgdx FileHandle.CopyTo for an internal directory behaves differently when run from a compiled JAR file. I made a work around. Thanks for following up so quickly.
