### ISSUE TITLE
Keep resources relative not working

### ISSUE THREAD

**Issue by Betalord** [raeleus/skin-composer#20]
The "Keep resources relative?" option in the settings window does not seem to have an effect. When this option is ticked and project is saved, resource paths are saved as absolute paths, for example:

```
{
atlasData: {
	atlasCurrent: true
	drawables: [
		{
			file: E:/Eclipse/workspace/Supergalactix/Supergalactix-core/razno/SGX UI Skin - MOJI POPRAVKI/sgxui_data/button.9.png
[...]
```
When changing the above path manually inside the .scmp file like this:
`file: sgxui_data/button.9.png`
the program will load the skin just fine, however upon saving it, it will overwrite it with the absolute path again, as shown before.

**Comment by raeleus** [comment]
This feature works by telling Skin Composer to just ignore the source path and find the named file in the relative assets path. This presents a problem when the source file still exists as it prioritizes the source path first. I'll have this fixed by the next version. Thanks.

**Comment by Betalord** [comment]
In the latest version 11, this problem is still present (it behaves exactly like in version 10A). That is, when "Keep relative paths" is ticked, it always saves them as absolute paths (even if paths are modified manually, they get rewritten with absolute ones).

**Comment by raeleus** [comment]
Sorry, I should have addressed that directly.  The file objects are serialized directly to the scmp file. That means full path and everything.  With the keep resources relative option selected, it chops off the path and looks in the data folder for the file  in the code, not  the  scmp  file. 

I mean,  I could have rewritten it so that the save files looks cleaner,  but the behavior would be the same. You can test by making a project file and link a resource to it. Make it keep resources relative,  then click save. Make a change to the original and it should not be reflected in your project.

Another thing, this is not an option to keep relative paths. By ticking the option, it makes duplicates of the source files in a data folder.

**Comment by aberkowski** [comment]
I don't know if @Betalord had the same issue but for me it creates a problem with saving file in repository. I want to save `.scmp` file in repository to be available not only for me. Saving full path in `.scmp` file makes me unable to share it with others. That is the first problem.
The second problem is: when I changed paths to relative inside `.scmp` file, project opened correctly but I've got an error when exporting to `.json`:
```
com.badlogic.gdx.utils.GdxRuntimeException: Error copying source file: project_data\Rubik-Regular.ttf (Absolute)
To destination: C:\Programowanie\android\assets\ui\Rubik-Regular.ttf (Absolute)
	at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:721)
	at com.badlogic.gdx.files.FileHandle.copyTo(FileHandle.java:606)
	at com.ray3k.skincomposer.dialog.DialogExport.lambda$writeFile$0(DialogExport.java:251)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:487)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error reading file: project_data\Rubik-Regular.ttf (Absolute)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:150)
	at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:719)
	... 5 more
Caused by: java.io.FileNotFoundException: project_data\Rubik-Regular.ttf (cannot find the specified path)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:146)
	... 6 more

```

My `.scmp` file looked like this now:
```
{
...
	freeTypeFonts: [
		{
			class: com.ray3k.skincomposer.data.FreeTypeFontData
			name: MyFnt
			file: project_data/Rubik-Regular.ttf
...
saveFile: project.scmp
...
}
```
