### ISSUE TITLE
Format bug

### ISSUE THREAD

**Issue by The28AWG** [raeleus/skin-composer#32]
An interesting error:
```
java.lang.NumberFormatException: For input string: "1,8"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.ray3k.skincomposer.dialog.DialogFreeTypeFont.populate(DialogFreeTypeFont.java:529)
	at com.ray3k.skincomposer.dialog.DialogFreeTypeFont.<init>(DialogFreeTypeFont.java:156)
	at com.ray3k.skincomposer.dialog.DialogFreeTypeFont.<init>(DialogFreeTypeFont.java:166)
	at com.ray3k.skincomposer.dialog.DialogFactory.showDialogFreeTypeFont(DialogFactory.java:727)
	at com.ray3k.skincomposer.dialog.DialogFonts.newFreeTypeFontDialog(DialogFonts.java:879)
	at com.ray3k.skincomposer.dialog.DialogFonts.access$200(DialogFonts.java:74)
	at com.ray3k.skincomposer.dialog.DialogFonts$3.changed(DialogFonts.java:196)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:178)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:383)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:54)

```
I tested it!
```java
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;

public class Test {

    @org.junit.Test
    public void test() {
        float gamma = 1.8f;
        DecimalFormat df = new DecimalFormat("#.#");
        System.out.println(df.format(gamma));
        System.out.println(Locale.getDefault());
        NumberFormat nf = NumberFormat.getNumberInstance(Locale.ROOT);
        DecimalFormat formatter = (DecimalFormat)nf;
        formatter.applyPattern("#.#");
        System.out.println(formatter.format(gamma));
    }
}
```
Output:

> 1,8
> ru_RU
> 1.8

**Comment by The28AWG** [comment]
https://github.com/raeleus/skin-composer/blob/8c860737514a771f8866a95a21e4fccfdee1861c/core/src/com/ray3k/skincomposer/dialog/DialogFreeTypeFont.java#L75
https://github.com/raeleus/skin-composer/blob/8c860737514a771f8866a95a21e4fccfdee1861c/core/src/com/ray3k/skincomposer/dialog/DialogFreeTypeFont.java#L529

**Comment by raeleus** [comment]
Thank you for looking into that! I had no idea that locale had an affect on DecimalFormat. I didn't even know that places beyond the US used a comma as a decimal separator. I added a fix for the next version. Sorry for the late response.

**Comment by Raduzz** [comment]
I have same issue. Please release .exe version with this bug fixed.

**Comment by raeleus** [comment]
I have included the fix with version 19. Thank you all.
