### ISSUE TITLE
NullPointerException after the creation of the 'custom drawable'

### ISSUE THREAD

**Issue by tscissors** [raeleus/skin-composer#39]
Hi! 
NullPointerException exception is thrown after I try to add new drawable.

Steps to reproduce :
1) Create new skin and save.
2) Create custom drawable with any name.
3) Add real drawable from any file.

System : arch linux 64bit.

PS Sorry for my poor english, im not a native speaker.

> java.lang.NullPointerException
	at com.ray3k.skincomposer.dialog.DialogDrawables.checkDuplicateDrawables(DialogDrawables.java:1149)
	at com.ray3k.skincomposer.dialog.DialogDrawables.drawablesSelected(DialogDrawables.java:1301)
	at com.ray3k.skincomposer.dialog.DialogDrawables.drawablesSelected(DialogDrawables.java:1290)
	at com.ray3k.skincomposer.dialog.DialogDrawables.newDrawableDialog(DialogDrawables.java:1228)
	at com.ray3k.skincomposer.dialog.DialogDrawables.access$300(DialogDrawables.java:84)
	at com.ray3k.skincomposer.dialog.DialogDrawables$2.changed(DialogDrawables.java:252)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:178)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:383)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:53)

**Comment by tscissors** [comment]
I found workaround:
Open .scmp file with text editor and change 'file' property for custom drawable from 'null' to any unique.
I hope it helps you.
SkinComposer is awesome! )

**Comment by raeleus** [comment]
Thank you so much for your kind words! I have already found a solution to this issue and it's available in the dev branch. I'll have a proper release in the next week or so. Thank you for the report and sorry for the inconvenience.

**Comment by tscissors** [comment]
Thank you!

**Comment by raeleus** [comment]
Solved in version 23
