### ISSUE TITLE
NullPointerException when saving after adding TrueTypeFont to VisUI project

### ISSUE THREAD

**Issue by Draika** [raeleus/skin-composer#40]
Steps to reproduce:

1. Show welcome screen, select VisUI template
2. Go to TextButton class
3. Go to font property and add font, choose "FreeTypeFont+" and add something
4. Select the font
5. Save - will crash program and not save the fonts

Problem does not occur on vanilla Scene2D project, only from VisUI template.

Also I'm getting a missing java.dll error whenever i try to launch to program, anyone know why? It lets me through to the main program. I'm using Java 1.8.0_181.

Error log:
> java.lang.NullPointerException
	at com.ray3k.skincomposer.data.ProjectData.makeResourcesRelative(ProjectData.java:294)
	at com.ray3k.skincomposer.data.ProjectData.save(ProjectData.java:309)
	at com.ray3k.skincomposer.data.ProjectData.save(ProjectData.java:321)
	at com.ray3k.skincomposer.MainListener.lambda$saveFile$6(MainListener.java:372)
	at com.ray3k.skincomposer.dialog.DialogLoading.lambda$show$0(DialogLoading.java:55)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.run(RunnableAction.java:42)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.act(RunnableAction.java:32)
	at com.badlogic.gdx.scenes.scene2d.actions.SequenceAction.act(SequenceAction.java:65)
	at com.badlogic.gdx.scenes.scene2d.Actor.act(Actor.java:96)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:46)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:221)
	at com.ray3k.skincomposer.Main.render(Main.java:281)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:53)

**Comment by raeleus** [comment]
I'll have to do some testing regarding both issues. With the java.dll error, are you using the windows installer version or the JAR file?

**Comment by Draika** [comment]
I have tried both and the same thing happens.
Which Java version should I be using to run this program?

**Comment by raeleus** [comment]
You should run it with Java 10. But the installer bundles Java 10, so that shouldn't be the issue. Thanks for testing. I'm finishing up new features and I'll be moving back into bug fixing very soon.

**Comment by raeleus** [comment]
I resolved the issue with the null pointer. Thanks for the report. Please wait for the new version to drop.

I'm having trouble reproducing the java.dll error. What OS version are you running?

**Comment by Draika** [comment]
glad to see that i helped!

Im running windows 7. I wonder if my current java install is overriding the bundled one?

**Comment by Draika** [comment]
can confirm that the error does not occur once i manually install java 10
