### ISSUE TITLE
Exception when deleting preview font

### ISSUE THREAD

**Issue by tscissors** [raeleus/skin-composer#41]
Hi!

Skin Composer crashes with this exception:
"java.lang.IllegalArgumentException: Missing LabelStyle font"

System: ubuntu64 18.04

Steps to reproduce:

1) Create a new project.
2) Create a new FreeType Font placeholder from any of preview fonts (i added my font to 'preview fonts' folder).
3) Save project and close Skin Composer.
4) Delete font from 'preview fonts' folder.
5) Open saved project and go to Menu -> Project -> Fonts.

```
java.lang.IllegalArgumentException: Missing LabelStyle font.
	at com.badlogic.gdx.scenes.scene2d.ui.Label.setStyle(Label.java:79)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.<init>(Label.java:73)
	at com.ray3k.skincomposer.dialog.DialogFonts.refreshTable(DialogFonts.java:476)
	at com.ray3k.skincomposer.dialog.DialogFactory.showDialogFonts(DialogFactory.java:161)
	at com.ray3k.skincomposer.dialog.DialogFactory.showDialogFonts(DialogFactory.java:165)
	at com.ray3k.skincomposer.dialog.DialogFactory.showFonts(DialogFactory.java:180)
	at com.ray3k.skincomposer.MainListener.rootEvent(MainListener.java:133)
	at com.ray3k.skincomposer.RootTable$RootTableListener.handle(RootTable.java:2682)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.ray3k.skincomposer.RootTable$MenuBarListener.menuClicked(RootTable.java:2593)
	at com.ray3k.skincomposer.MenuButton$MenuButtonListener.handle(MenuButton.java:249)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.ray3k.skincomposer.MenuButton$1.menuClicked(MenuButton.java:66)
	at com.ray3k.skincomposer.MenuList$MenuListListener.handle(MenuList.java:285)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:143)
	at com.ray3k.skincomposer.MenuList$1.changed(MenuList.java:194)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:178)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:383)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:53)
```

**Comment by raeleus** [comment]
Thanks for the detailed report. I'll have it resolved in the next version.
