### ISSUE TITLE
Opening project vs23 in vs24 editor fails: Named value not found: parent 

### ISSUE THREAD

**Issue by Raduzz** [raeleus/skin-composer#44]
java.lang.IllegalArgumentException: Named value not found: parent
	at com.badlogic.gdx.utils.JsonValue.getString(JsonValue.java:651)
	at com.ray3k.skincomposer.data.StyleData.read(StyleData.java:309)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:928)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:981)

I guess because I use custom classes. You added the parent option but in my project there are no parents.

**Comment by raeleus** [comment]
Thanks for finding this one. I have the fix and will upload a new version soon.
