### ISSUE TITLE
SON read error

### ISSUE THREAD

**Issue by nerondes** [raeleus/skin-composer#48]
JSON : 
{
  "com.badlogic.gdx.graphics.g2d.BitmapFont": {
    "default-font": {
      "file": "fonts/ui_font_32.fnt"
    }
  },
  "com.badlogic.gdx.graphics.Color": {
    "white": {
      "a": 1,
      "b": 1,
      "g": 1,
      "r": 1
    },
    "black": {
      "a": 1,
      "b": 0,
      "g": 0,
      "r": 0
    },
    "gray": {
      "a": 1,
      "b": 0.5,
      "g": 0.5,
      "r": 0.5
    }
  },
  "com.badlogic.gdx.scenes.scene2d.ui.TextButton$TextButtonStyle": {
    "default": {
      "down": "button-down",
      "up": "button",
      "font": "default-font",
      "fontColor": "white",
      "downFontColor": "black",
      "overFontColor": "gray"
    }
  },
  "com.badlogic.gdx.scenes.scene2d.ui.Label$LabelStyle": {
    "default": {
      "font": "default-font",
      "fontColor": "white"
    }
  },
  "com.badlogic.gdx.scenes.scene2d.ui.CheckBox$CheckBoxStyle": {
    "default": {
      "down": "button-down",
      "up": "button",
      "checkboxOn": "check-on",
      "checkboxOff": "check-off",
      "font": "default-font",
      "fontColor": "white",
      "downFontColor": "black",
      "overFontColor": "gray"
    }
  }
}

error log :  

com.ray3k.skincomposer.dialog.DialogImport: Error attempting to import JSON
java.lang.NullPointerException
	at com.ray3k.skincomposer.data.JsonData.readFile(JsonData.java:168)
	at com.ray3k.skincomposer.dialog.DialogImport.lambda$importFile$2(DialogImport.java:182)
	at com.ray3k.skincomposer.dialog.DialogLoading.lambda$show$0(DialogLoading.java:55)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.run(RunnableAction.java:42)
	at com.badlogic.gdx.scenes.scene2d.actions.RunnableAction.act(RunnableAction.java:32)
	at com.badlogic.gdx.scenes.scene2d.actions.SequenceAction.act(SequenceAction.java:65)
	at com.badlogic.gdx.scenes.scene2d.Actor.act(Actor.java:98)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:46)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:222)
	at com.ray3k.skincomposer.Main.render(Main.java:246)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:53)

**Comment by raeleus** [comment]
Sorry, I don't have enough info to reproduce this issue.
