### ISSUE TITLE
Jar file crash at start (MacOsX)

### ISSUE THREAD

**Issue by aramoki** [raeleus/skin-composer#53]
Her is terminal error log

Last login: Sat Mar  9 17:15:54 on ttys000
Aramoks-iMac:~ aramok$ java -jar /Users/aramok/Downloads/skin_composer_mac.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1831)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:450)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:380)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:53)
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
	at org.lwjgl.glfw.EventLoop$OffScreen.<clinit>(EventLoop.java:39)
	... 6 more
AL lib: (EE) alc_cleanup: 1 device not closed
Aramoks-iMac:~ aramok$

**Comment by raeleus** [comment]
To start the JAR version of Skin Composer on Mac, you have to launch it with a certain argument as explained in the error you see there.
Make sure you've downloaded the skin_composer_mac.jar. Open Terminal, navigate to the folder where Skin Composer is located. Then use the following command:

`java -jar -XstartOnFirstThread skin_composer_mac.jar`

I'm working on making this simpler and more reliable with an app package, but this is the best way to do it for now. Thank you for the report.
