### ISSUE TITLE
Custom class duplication Exception

### ISSUE THREAD

**Issue by Raduzz** [raeleus/skin-composer#54]
Exception:

`java.lang.IndexOutOfBoundsException:` index can't be >= size: 24 >= 24
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:131)
	at com.badlogic.gdx.scenes.scene2d.ui.HorizontalGroup.layoutWrapped(HorizontalGroup.java:259)
	at com.badlogic.gdx.scenes.scene2d.ui.HorizontalGroup.layout(HorizontalGroup.java:136)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:114)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:788)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:114)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.layout(ScrollPane.java:534)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:114)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.getPrefWidth(ScrollPane.java:651)
	at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:74)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:838)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:404)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.getPrefWidth(SplitPane.java:171)
	at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:74)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:838)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:404)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.getPrefWidth(SplitPane.java:173)
	at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:74)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:838)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:964)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:760)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:114)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:101)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.ray3k.skincomposer.Main.render(Main.java:239)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:31)`

When duplicating:

`{
			fullyQualifiedName: com.xxx.scene2d.BoxDeskCreate$BoxDeskCreateStyle
			displayName: BoxDeskCreate
			styles: [
				{
					name: default
					properties: [
						{
							name: background
							type: DRAWABLE
							value: boxMainHdpi
						}
						{
							name: bgHeader
							type: DRAWABLE
							value: null
						}
						{
							name: bgBody
							type: DRAWABLE
							value: boxInnerHdpi
						}
						{
							name: bgFooter
							type: DRAWABLE
							value: null
						}
						{
							name: colorHeader
							type: COLOR
							value: white
						}
						{
							name: colorBody
							type: COLOR
							value: white
						}
						{
							name: colorFooter
							type: COLOR
							value: null
						}
						{
							name: fontHeader
							type: FONT
							value: tttl-font-01
						}
						{
							name: fontBody
							type: FONT
							value: tttl-font-02
						}
						{
							name: fontFooter
							type: FONT
							value: null
						}
						{
							name: scrollPane
							type: TEXT
							value: selectImages
						}
						{
							name: checkBox
							type: TEXT
							value: ""
						}
						{
							name: buttonOK
							type: TEXT
							value: red
						}
						{
							name: buttonCancel
							type: TEXT
							value: orange
						}
						{
							name: fontTitle
							type: FONT
							value: tttl-font-01
						}
						{
							name: colorTitle
							type: COLOR
							value: green
						}
						{
							name: fontLabel
							type: FONT
							value: tttl-font-02
						}
						{
							name: colorLabel
							type: COLOR
							value: gold
						}
						{
							name: bgScreen
							type: DRAWABLE
							value: null
						}
						{
							name: textfield
							type: TEXT
							value: beige
						}
						{
							name: selectbox
							type: TEXT
							value: beige
						}
					]
					deletable: false
				}
			]
			templateStyle: {
				name: template
				properties: [
					{
						name: background
						type: DRAWABLE
						value: null
					}
					{
						name: background
						type: DRAWABLE
						value: null
					}
					{
						name: bgHeader
						type: DRAWABLE
						value: null
					}
					{
						name: bgBody
						type: DRAWABLE
						value: null
					}
					{
						name: bgFooter
						type: DRAWABLE
						value: null
					}
					{
						name: colorHeader
						type: COLOR
						value: null
					}
					{
						name: colorBody
						type: COLOR
						value: null
					}
					{
						name: colorFooter
						type: COLOR
						value: null
					}
					{
						name: fontHeader
						type: FONT
						value: null
					}
					{
						name: fontBody
						type: FONT
						value: null
					}
					{
						name: fontFooter
						type: FONT
						value: null
					}
					{
						name: scrollPane
						type: TEXT
						value: ""
					}
					{
						name: checkBox
						type: TEXT
						value: ""
					}
					{
						name: buttonOK
						type: TEXT
						value: ""
					}
					{
						name: buttonCancel
						type: TEXT
						value: ""
					}
					{
						name: fontTitle
						type: FONT
						value: null
					}
					{
						name: colorTitle
						type: COLOR
						value: null
					}
					{
						name: fontLabel
						type: FONT
						value: null
					}
					{
						name: colorLabel
						type: COLOR
						value: null
					}
					{
						name: bgScreen
						type: DRAWABLE
						value: null
					}
					{
						name: textfield
						type: TEXT
						value: ""
					}
					{
						name: selectbox
						type: TEXT
						value: ""
					}
				]
				deletable: true
			}
			declareAfterUIclasses: false
		}`

**Comment by raeleus** [comment]
Thanks for the report. I'll look into it.

**Comment by raeleus** [comment]
I'm having trouble reproducing this one. Where there any other specifics that could help me out here?

**Comment by Raduzz** [comment]
If I create new project add and remove custom classes then there is no problem.
I have problem with my current project. I was analyzing the bug for two hours today.
I took my project and removed custom classes in text editor one by one and test it then in skin composer app.

I finished with just two custom classes [Box, BoxSettings] in the project. 
I can browse them normally in skin composer. I remove Box, then Exception occurs. But problem is not Box but the BoxSettings the custom class with is automatically displayed after Box is removed.

I removed as much as properties as I could. If I remove one more property from BoxSetting then exception is gone (the one after removing the Box).

Hope it helps.

`customClasses: [
		{
			fullyQualifiedName: com.tictactoe_league.scene2d.Box$BoxStyle
			displayName: Box
			styles: [
				{
					name: default
					properties: [
						{
							name: background
							type: DRAWABLE
							value: AzureL
						}
					]
					deletable: false
				}
			]
			templateStyle: {
				name: template
				properties: [
					{
						name: background
						type: DRAWABLE
						value: null
					}
				]
				deletable: true
			}
			declareAfterUIclasses: false
		}
		{
			fullyQualifiedName: com.tictactoe_league.scene2d.BoxSettings$BoxSettingsStyle
			displayName: BoxSettings
			styles: [
				{
					name: default
					properties: [
						{
							name: bgBody
							type: DRAWABLE
							value: boxInnerHdpi
						}
						{
							name: bgFooter
							type: DRAWABLE
							value: null
						}
						{
							name: colorBody
							type: COLOR
							value: white
						}
						{
							name: fontHeader
							type: FONT
							value: tttl-font-01
						}																
					]
					deletable: false
				}
			]
			templateStyle: {
				name: template
				properties: [
					{
						name: bgBody
						type: DRAWABLE
						value: null
					}
					{
						name: bgFooter
						type: DRAWABLE
						value: null
					}
					{
						name: colorBody
						type: COLOR
						value: null
					}
					{
						name: fontHeader
						type: FONT
						value: null
					}														
				]
				deletable: true
			}
			declareAfterUIclasses: false
		}
		
	]`

**Comment by raeleus** [comment]
I'm still not able to reproduce this issue in ver. 29 or ver. 30. I'm really sorry you spent all this time trying to debug it. I even just copy pasted the values directly into the save and nothing out of the ordinary happens. I'll leave this issue up in case I stumble upon it myself, but it's not going to be resolved for the next release. Sorry!
