### ISSUE TITLE
Crash on Font creation with many image files

### ISSUE THREAD

**Issue by MrStahlfelge** [raeleus/skin-composer#57]
If I try to generate a BitmapFont that leads to more than a single png file, SkinComposer crashes:

```
java.lang.RuntimeException: Actor: Table
|  okButton
|  |  Label: Generate Font
|  saveButton
|  |  Label: Save Settings
|  loadButton
|  |  Label: Load Settings
|
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:202)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:158)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:131)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:94)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:86)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:205)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:390)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:31)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: font40.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
	at com.ray3k.skincomposer.desktop.Launcher.writeFont(Launcher.java:336)
	at com.ray3k.skincomposer.data.FreeTypeFontData.writeFontToFile(FreeTypeFontData.java:231)
	at com.ray3k.skincomposer.dialog.DialogBitmapFont.result(DialogBitmapFont.java:138)
	at com.badlogic.gdx.scenes.scene2d.ui.Dialog$2.changed(Dialog.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 12 more
```

It's correct, there is no font40.png but font40_0.png, font40_1.png and so on. I would like to have just one image file, but the setting for texture packer about maximum sized is ignored here.

**Comment by raeleus** [comment]
I resolved the crash, but libGDX's utilities to create a font at large fonts is very faulty. I'll have to write my own implementation some time in the future. Sorry!
