### ISSUE TITLE
NullPointerException when creating a new custom drawable

### ISSUE THREAD

**Issue by Spikatrix** [raeleus/skin-composer#67]
Steps to reproduce:
 - Open SkinComposer and load any sample skins, say, Neon UI
 - Go to 'Project > Drawables' and click on the 'Custom +' button
 - Type any name for the custom drawable and press the 'OK' button

Result:
```
java.lang.NullPointerException
    at com.ray3k.skincomposer.data.ProjectData.makeResourcesRelative(ProjectData.java:315)
    at com.ray3k.skincomposer.data.ProjectData.makeResourcesRelative(ProjectData.java:346)
    at com.ray3k.skincomposer.dialog.DialogDrawables.lambda$customDrawableDialog$10(DialogDrawables.java:1922)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:153)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
    at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:31)
```

This crash does not happen when I create a new project instead of loading a sample project.

I'm using Linux, Skin Composer version 34

**Comment by raeleus** [comment]
This will be resolved with version 35. Thank you very much for the report!
