### ISSUE TITLE
java.lang.IllegalArgumentException: Missing LabelStyle font

### ISSUE THREAD

**Issue by voodoosoft** [raeleus/skin-composer#8]
When choosing the label from the widget drop down box, skin composer crashes: 

java.lang.IllegalArgumentException: Missing LabelStyle font.
	at com.badlogic.gdx.scenes.scene2d.ui.Label.setStyle(Label.java:78)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.<init>(Label.java:72)
	at com.ray3k.skincomposer.panel.PanelPreviewProperties.render(PanelPreviewProperties.java:1100)
	at com.ray3k.skincomposer.panel.PanelPreviewProperties.populate(PanelPreviewProperties.java:981)
	at com.ray3k.skincomposer.panel.PanelClassBar$5.changed(PanelClassBar.java:138)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:218)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.set(Selection.java:103)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox.setSelected(SelectBox.java:260)
	at com.ray3k.skincomposer.panel.PanelClassBar$1.changed(PanelClassBar.java:87)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:218)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:52)
	at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:46)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxList$2.clicked(SelectBox.java:364)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:198)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:257)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:41)

**Comment by raeleus** [comment]
Is there any chance I can see the font files you're using? That might address both of your issues there.

**Comment by voodoosoft** [comment]
I just grabbed the arial font from the gdx.jar

**Comment by raeleus** [comment]
I can't reproduce the issue. The error message sounds like something I've already fixed though. Please download the newest version of Skin Composer that I just uploaded: https://github.com/raeleus/skin-composer/releases

Create a new project and use the same font files that I tested:

[arial font.zip](https://github.com/raeleus/skin-composer/files/491455/arial.font.zip)

Please let me know if it persists with the new project. I'm sorry for any inconvenience this may be to you!

**Comment by voodoosoft** [comment]
Seems to work now. I could repair my old file by copying over the lable section. Thanks !

**Comment by raeleus** [comment]
No problem. I'm glad you've found some use for my app.
