### ISSUE TITLE
Can't create TTF font

### ISSUE THREAD

**Issue by imcasper** [raeleus/skin-composer#87]
I run jar file or use "SkinComposer" under linux (result equal)

My Actions:
Add->Free type Font -> (enter font name "Verdana" or "Arial" for sample) -> Generate font...

Expected behaviour:
Creating a font or show error message in the app

Result:
java.lang.RuntimeException: Actor: Table
|  okButton
|  |  Label: Generate Font
|  saveButton
|  |  Label: Save Settings
|  loadButton
|  |  Label: Load Settings
|
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:158)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:132)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:95)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:69)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:352)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:86)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:405)
Caused by: java.lang.NullPointerException
	at com.ray3k.skincomposer.dialog.DialogFonts.refreshTable(DialogFonts.java:521)
	at com.ray3k.skincomposer.dialog.DialogFonts.sortFontsAZ(DialogFonts.java:818)
	at com.ray3k.skincomposer.dialog.DialogFonts.sortBySelectedMode(DialogFonts.java:801)
	at com.ray3k.skincomposer.dialog.DialogFonts$16.fontAdded(DialogFonts.java:1021)
	at com.ray3k.skincomposer.dialog.DialogFreeTypeFont.result(DialogFreeTypeFont.java:226)
	at com.badlogic.gdx.scenes.scene2d.ui.Dialog$2.changed(Dialog.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 12 more

**Comment by raeleus** [comment]
Hello. This is resolved with version 40. Please standby, I'm working on a release soon. Thanks for taking the time to make a report!
