### ISSUE TITLE
font file gets empties

### ISSUE THREAD

**Issue by voodoosoft** [raeleus/skin-composer#9]
When exporting a skin, the previously assigned fnt-file is left with a file size of 0.

**Comment by raeleus** [comment]
Let me know if this resurfaces. Thanks.

**Comment by voodoosoft** [comment]
Still happens every time on export and/or saving.

**Comment by raeleus** [comment]
Alright, I'll have to tackle this one throughout the week. What OS are you running? By "previously assigned fnt-file" are you referring to the original file that you placed into the program or the copy that's created when you export? Are you making sure to export into a separate folder?

**Comment by voodoosoft** [comment]
Sorry, I am giving up on it for now, got the next exception: 

java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.ui.List.layout(List.java:106)
	at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
	at com.badlogic.gdx.scenes.scene2d.ui.List.getPrefWidth(List.java:257)
	at com.badlogic.gdx.scenes.scene2d.ui.List.<init>(List.java:64)
	at com.ray3k.skincomposer.panel.PanelPreviewProperties.render(PanelPreviewProperties.java:1097)
	at com.ray3k.skincomposer.panel.PanelStyleProperties$ColorUndoable.redo(PanelStyleProperties.java:397)
	at com.ray3k.skincomposer.Main.addUndoable(Main.java:562)
	at com.ray3k.skincomposer.panel.PanelStyleProperties$3.lambda$changed$42(PanelStyleProperties.java:154)
	at com.ray3k.skincomposer.dialog.DialogColors.result(DialogColors.java:558)
	at com.ray3k.skincomposer.dialog.DialogColors$12.changed(DialogColors.java:384)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:198)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:257)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:41)

**Comment by raeleus** [comment]
I was able to reproduce the issue by exporting to the same folder that the original file is located. Apparently LibGDX doesn't like copying a file back on to itself. I'll add some lines to prevent that from happening again. I'm sorry that I've never noticed that. I always make a separate folder for my exports. I suggest  you do that too until I add the fix.

As for your second error, I believe that is from the now invalid font screwing things up. List requires a font. I would hope it will clear up when you add the font back in. Thanks for hanging in there.
